<a href="https://colab.research.google.com/github/abhishekcs10/tf_practice_ml_keras/blob/master/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import tensorflow as tf
import numpy as np
from __future__ import print_function
a=np.random.uniform(low=0.5, high=12.3,size=(4,3))
b=np.random.randint(low=1,size=(4,5))
print(a)
x_tensor=tf.placeholder(tf.float32,shape=(4,3))
m_tensor=tf.placeholder(tf.float32,shape=(5,4))
c_tensor=np.random.uniform(1,5,size=(5,1))
y_tensor=tf.add(tf.matmul(m_tensor,x_tensor),c_tensor)


  

[[ 5.14434663 11.28647508 11.74254425]
 [11.75542743  6.89771521  4.98037497]
 [ 1.46141869  8.00514924  9.35258205]
 [ 1.0765045   8.96105003  9.27760684]]
[[1.6683549 1.6683549 1.6683549]
 [4.5554233 4.5554233 4.5554233]
 [1.0554993 1.0554993 1.0554993]
 [1.1658249 1.1658249 1.1658249]
 [2.0021355 2.0021355 2.0021355]]


In [21]:
with tf.Session() as sess:
  d=sess.run(y_tensor, {x_tensor: a,m_tensor: b.T})
  print(d)
  print(type(d))

[[1.6683549 1.6683549 1.6683549]
 [4.5554233 4.5554233 4.5554233]
 [1.0554993 1.0554993 1.0554993]
 [1.1658249 1.1658249 1.1658249]
 [2.0021355 2.0021355 2.0021355]]
<class 'numpy.ndarray'>


<tf.Operation 'PrintV2_1' type=PrintV2>